name: CHANGELOG automation with git-cliff

on:
  # Runs on pushes targeting the default branch
  push:
    branches: 
      - "master"
    paths-ignore:
      - 'docs/**'
      
jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --sort newest --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/Negrini085/PhotoNim.git master
